walk(data_scripts, run_script)
Running adae.R...
Dropping shared vars from raw: STUDYID, SUBJID, SITEID, COUNTRY, RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC, RFPENDTC, SCRFDT, FRVDT, DTHDTC, DTHADY, DTHFL, LDDTHELD, LDDTHGR1, DTH30FL, DTHA30FL, DTHDOM, DTHB30FL, REGION1, DMDTC, DMDY, AGE, AGEU, AGEGR1, SEX, RACE, RACEGR1, ETHNIC, SAFFL, ARM, ARMCD, ACTARM, ACTARMCD, TRT01P, TRT01A, TRTSDT, TRTSDTM, TRTSTMF, TRTEDT, TRTEDTM, TRTETMF, EOSSTT, EOSDT, RFICDTC, RANDDT, LSTALVDT, TRTDURD, DTHDT, DTHDTF, DTHCAUS, DTHCGR1
Successfully processed adae.R
Saving adae dataset...
✔ Saving "adae" to "data/adae.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adae...
Successfully documented adae
---------------------------------
Running adaeocmq.R...
Dropping shared vars from raw: STUDYID, SUBJID, SITEID, COUNTRY, RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC, RFPENDTC, SCRFDT, FRVDT, DTHDTC, DTHADY, DTHFL, LDDTHELD, LDDTHGR1, DTH30FL, DTHA30FL, DTHDOM, DTHB30FL, REGION1, DMDTC, DMDY, AGE, AGEU, AGEGR1, SEX, RACE, RACEGR1, ETHNIC, SAFFL, ARM, ARMCD, ACTARM, ACTARMCD, TRT01P, TRT01A, TRTSDT, TRTSDTM, TRTSTMF, TRTEDT, TRTEDTM, TRTETMF, EOSSTT, EOSDT, RFICDTC, RANDDT, LSTALVDT, TRTDURD, DTHDT, DTHDTF, DTHCAUS, DTHCGR1
Successfully processed adaeocmq.R
Saving adaeocmq dataset...
✔ Saving "adaeocmq" to "data/adaeocmq.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adaeocmq...
Successfully documented adaeocmq
---------------------------------
Running adagocmq.R...
Dropping shared vars from raw: STUDYID, SUBJID, SITEID, COUNTRY, RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC, RFPENDTC, SCRFDT, FRVDT, DTHDTC, DTHADY, DTHFL, LDDTHELD, LDDTHGR1, DTH30FL, DTHA30FL, DTHDOM, DTHB30FL, REGION1, DMDTC, DMDY, AGE, AGEU, AGEGR1, SEX, RACE, RACEGR1, ETHNIC, SAFFL, ARM, ARMCD, ACTARM, ACTARMCD, TRT01P, TRT01A, TRTSDT, TRTSDTM, TRTSTMF, TRTEDT, TRTEDTM, TRTETMF, EOSSTT, EOSDT, RFICDTC, RANDDT, LSTALVDT, TRTDURD, DTHDT, DTHDTF, DTHCAUS, DTHCGR1
Error processing adagocmq.R: argument 63 is empty
Running adcm.R...
Dropping shared vars from raw: STUDYID, SUBJID, SITEID, COUNTRY, RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC, RFPENDTC, SCRFDT, FRVDT, DTHDTC, DTHADY, DTHFL, LDDTHELD, LDDTHGR1, DTH30FL, DTHA30FL, DTHDOM, DTHB30FL, REGION1, DMDTC, DMDY, AGE, AGEU, AGEGR1, SEX, RACE, RACEGR1, ETHNIC, SAFFL, ARM, ARMCD, ACTARM, ACTARMCD, TRT01P, TRT01A, TRTSDT, TRTSDTM, TRTSTMF, TRTEDT, TRTEDTM, TRTETMF, EOSSTT, EOSDT, RFICDTC, RANDDT, LSTALVDT, TRTDURD, DTHDT, DTHDTF, DTHCAUS, DTHCGR1
Successfully processed adcm.R
Saving adcm dataset...
✔ Saving "adcm" to "data/adcm.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adcm...
Successfully documented adcm
---------------------------------
Running addili.R...
Error processing addili.R: argument 63 is empty
Running adeg.R...
Dropping shared vars from raw: STUDYID, SUBJID, SITEID, COUNTRY, RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC, RFPENDTC, SCRFDT, FRVDT, DTHDTC, DTHADY, DTHFL, LDDTHELD, LDDTHGR1, DTH30FL, DTHA30FL, DTHDOM, DTHB30FL, REGION1, DMDTC, DMDY, AGE, AGEU, AGEGR1, SEX, RACE, RACEGR1, ETHNIC, SAFFL, ARM, ARMCD, ACTARM, ACTARMCD, TRT01P, TRT01A, TRTSDT, TRTSDTM, TRTSTMF, TRTEDT, TRTEDTM, TRTETMF, EOSSTT, EOSDT, RFICDTC, RANDDT, LSTALVDT, TRTDURD, DTHDT, DTHDTF, DTHCAUS, DTHCGR1
Successfully processed adeg.R
Saving adeg dataset...
✔ Saving "adeg" to "data/adeg.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adeg...
Successfully documented adeg
---------------------------------
Running adex.R...
Dropping shared vars from raw: STUDYID, SUBJID, SITEID, COUNTRY, RFSTDTC, RFENDTC, RFXSTDTC, RFXENDTC, RFPENDTC, SCRFDT, FRVDT, DTHDTC, DTHADY, DTHFL, LDDTHELD, LDDTHGR1, DTH30FL, DTHA30FL, DTHDOM, DTHB30FL, REGION1, DMDTC, DMDY, AGE, AGEU, AGEGR1, SEX, RACE, RACEGR1, ETHNIC, SAFFL, ARM, ARMCD, ACTARM, ACTARMCD, TRT01P, TRT01A, TRTSDT, TRTSDTM, TRTSTMF, TRTEDT, TRTEDTM, TRTETMF, EOSSTT, EOSDT, RFICDTC, RANDDT, LSTALVDT, TRTDURD, DTHDT, DTHDTF, DTHCAUS, DTHCGR1
Successfully processed adex.R
Saving adex dataset...
✔ Saving "adex" to "data/adex.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adex...
Successfully documented adex
---------------------------------
Running adexsum.R...
Successfully processed adexsum.R
Saving adexsum dataset...
✔ Saving "adexsum" to "data/adexsum.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adexsum...
Successfully documented adexsum
---------------------------------
Running adlb.R...
Error processing adlb.R: argument 63 is empty
Running adpc.R...
Successfully processed adpc.R
Saving adpc dataset...
✔ Saving "adpc" to "data/adpc.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adpc...
Successfully documented adpc
---------------------------------
Running adsl.R...
Successfully processed adsl.R
Saving adsl dataset...
✔ Saving "adsl" to "data/adsl.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adsl...
Successfully documented adsl
---------------------------------
Running adttesaf.R...
Successfully processed adttesaf.R
Saving adttesaf dataset...
✔ Saving "adttesaf" to "data/adttesaf.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
Generating documentation for adttesaf...
Successfully documented adttesaf
---------------------------------
---------------------------------
Running advs.R...
Successfully processed advs.R
Saving advs dataset...
✔ Saving "advs" to "data/advs.rda".
☐ Document your data (see <https://r-pkgs.org/data.html>).
